spring.application.name=spring-root-test
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
spring.oss.BUCKET_NAME=fuxianan-upload
spring.oss.ENDPOINT=oss-cn-hangzhou.aliyuncs.com

# ????
wx.miniapp.appid=wx665999547f43eb35
wx.miniapp.secret=a72e4de0d160e26a4d3abc24717c9c9c

# JWT ??
jwt.secret=fuxianan19961003jwtsecret
jwt.expire=7200